services:
  mysql:
    image: crpi-kj0h1ihlbijkcjuf.cn-shanghai.personal.cr.aliyuncs.com/dev-practice/my-mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: furukawa
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p123456"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    depends_on:
      mysql:
        condition: service_healthy
    image: crpi-kj0h1ihlbijkcjuf.cn-shanghai.personal.cr.aliyuncs.com/dev-practice/furukawa-backend:v1.0.0
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ci
      OSS_ACCESS_KEY_ID: "${OSS_ACCESS_KEY_ID}"
      OSS_ACCESS_KEY_SECRET: "${OSS_ACCESS_KEY_SECRET}"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge