services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: furukawa

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "-p123456", "-e", "USE furukawa;" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c '
        until mysql -h mysql -P 3306 -u root -p123456 -e "SELECT 1" >/dev/null 2>&1;
        do
          echo "等待 MySQL 启动...";
          sleep 2;
        done;
        echo "MySQL 已就绪，启动应用...";
        java -jar /app/app.jar
      '

    image: crpi-kj0h1ihlbijkcjuf.cn-shanghai.personal.cr.aliyuncs.com/dev-practice/furukawa-backend:v1.0.0
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ci
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/furukawa?useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
