spring:
  datasource:
    url: jdbc:mysql://mysql:3306/furukawa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      enabled: false

jwt:
  secret: Na_gi_sa_O_re_wa_ko_ko_ni_ru_zo_123456789

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSSS_ACCESS_KEY_SECRET}
    bucketName: okazaki-bluewhale

