spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furukawa?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      enabled: false

jwt:
  secret: Na_gi_sa_O_re_wa_ko_ko_ni_ru_zo_123456789

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5t8xrpCkS7fhVUmb7JRV
    accessKeySecret: BpihAZNaiecy40ex7WVYCxcdnvm3BR
    bucketName: okazaki-bluewhale



